<?php

return array(
    "object"    => "odmessage",
    "typeObj"   => "odcontained",
    "template"  => "odmessage.twig",
    "type"      => "",
    "title"     => "",
    "body"      => "",
    "size"      => "normal",
    "action"    => "init",
    "sound"     => true,
    "soundPath" => __DIR__ . "/../../../../../public/objets/odcontained/odmessage/sounds",
    "delay"     => 3000, // en millisecondes
    "position"  => 'bottom right',

    "resources" => array(
        "css" => array( "css/Lobibox.css", ),
        "js"  => array( "js/Lobibox.js", )
    )
);
