<?php
return array(
    "object"        => "ocselect",
    "typeObj"       => "odcontent",
    "template"      => "ocselect.twig",
    "options"       => array(),
    "multiple"      => false,
    "select2"       => false,
    "placeholder"   => "",
    "label"         => "",
    "paramsSelect2" => array(
        "allowClear"    => false,
        "searchBox"     => true,
        "langue"        => 'fr',
    ),
    "resources" => array(
        "css"           => array(
            "css/select2.css",
            "css/select2-bootstrap.css",
        ),
        "js"            => array( "js/select2.js" ),
    ),
);
