<?php

return array(
    "object"        => "osdialog",
    "typeObj"       => "oscontainer",
    "template"      => "osdialog.twig",
    "transition"    => "none",
    "title"         => "",
    "scrolling"     => true,
    "scalePhoto"    => true,
    "closeButton"   => true,
    "width"         => false,
    "height"        => false,
    "initialWidth"  => false,
    "initialHeight" => false,
    "maxWidth"      => false,
    "maxHeight"     => false,
    "reposition"    => true,
    "fixed"         => false,
    "resources"     => array(
        "css" => array(  ),
        "js"  => array( "js/jquery.colorbox.js" )
    )
);