<?php

/**
 * Generated by ZF2ModuleCreator
 */

namespace GraphicObjectTemplating;

use Zend\ModuleManager\Feature\AutoloaderProviderInterface;
use Zend\ModuleManager\Feature\ConfigProviderInterface;
use GraphicObjectTemplating\View\Helper\GotRender;
use Zend\ModuleManager\Feature\ViewHelperProviderInterface;
use Zend\Mvc\MvcEvent;
use Zend\Session\Config\SessionConfig;
use Zend\Session\Container;
use Zend\Session\SessionManager;

class Module implements AutoloaderProviderInterface, ConfigProviderInterface,
    ViewHelperProviderInterface
{
    public function onBootstrap(MvcEvent $e)
    {
        $this->initSession(array(
            'remember_me_seconds' => 900, // 1/4 heure de temps de vie (rememberMe)
            'gc_maxlifetime' => 1800,     // 1/2 heure de temps de vie max
            'gc_divisor' => 1,
            'use_cookies' => true,
            'cookie_httponly' => true,
        ));
    }

    /**
     * Returns configuration to merge with application configuration
     *
     * @return array|\Traversable
     */
    public function getConfig()
    {
        return include __DIR__ . '/config/module.config.php';
    }

    /**
     * Return an array for passing to Zend\Loader\AutoloaderFactory.
     *
     * @return array
     */
    public function getAutoloaderConfig()
    {
        return array(
            'Zend\Loader\StandardAutoloader' => array(
                'namespaces' => array(
                    // Autoload all classes from namespace 'GraphicObjectTemplating' from '/module/GraphicObjectTemplating/src/GraphicObjectTemplating'
                    __NAMESPACE__ => __DIR__ . '/src/' . __NAMESPACE__,
                )
            )
        );
    }

    public function getViewHelperConfig()
    {
        return array(
            'factories' => array(
                'gotRender'    => 'GraphicObjectTemplating\View\Helper\GotRenderFactory',
                'gotBootstrap' => 'GraphicObjectTemplating\View\Helper\GotBootstrapFactory',
                'gotHeader'    => 'GraphicObjectTemplating\View\Helper\GotHeaderFactory',
                'gotAjax'      => 'GraphicObjectTemplating\View\Helper\GotAjaxFactory',
            ),
        );
    }
    
    /*
     * impltentation de Session
     */
    public function initSession($config)
    {
        $sessionConfig = new SessionConfig();
        $sessionConfig->setOptions($config);
        $sessionManager = new SessionManager($sessionConfig);
        $sessionManager->start();
        Container::setDefaultManager($sessionManager);
    }
}