<?php
return array(
    "object"        => "octabs",
    "typeObj"       => "ocobjects",
    "template"      => "octabs.twig",
    "title"         => "",
    "tabs"          => array(),
    "btns"          => array(),
    "navigation"    => false,
    "selectable"    => true,
    "resources" => array(
        "css"           => array( "css/tabs.css" ),
        "js"            => array( "js/tabs.js" ),
    )
);
