<?php
return array(
    "object"            => "odtreeview",
    "typeObj"           => "odcontained",
    "template"          => "odtreeview.twig",
    "label"             => "",
    "searchLabel"       => "",
    "searchPlaceholder" => "",
    "multiple"          => false,
    "checkbox"          => true,
    "resources"         => array(
        "css"               => array( "css/bootstrap-treeview.min.css"),
        "js"                => array( "js/bootstrap-treeview.min.js" ),
    )
);