<?php

return array(
    "object"     => "ocbutton",         // *
    "typeObj"    => "odcontent",        // *
    "template"   => "ocbutton.twig",    // *
    "type"       => "custom",           //**
    "label"      => "",                 // *
    "icon"       => "",                 // *
    'state'      => 'true',             // *
    'event'      => "click", // figé non affectable
    'callback'   => "",                 // *
    'nature'     => 'btn btn-default'
);
