<?php

return array(
    'id'           => '',
    'template'     => '',
    'display'      => 'block',
    'style'        => '',
    'classes'      => '',
    'widthBT'      => array(),
    'state'        => true,
    'infoBulle'    => array(
        'title'         => "",
        'content'       => "",
        'type'          => 'tooltip',
        'placement'     => 'top',
        'trigger'       => 'hover',
        'delay-show'    => 0,
        'delay-hide'    => 400,
    ),

    // pour l'application
    'aclReference' => '',
);