<?php

return array(
    "id"           => "",
    "template"     => "",
    "display"      => "block",
    "style"        => "",
    "classes"      => "",
    "widthBT"      => array(),
    "state"        => true,
    "infoBulle"    => array(
        "title"         => "",
        "content"       => "",
        "html"          => false,
        "type"          => "tooltip",
        "placement"     => "top",
        "trigger"       => "hover",
        "delay-show"    => 0,
        "delay-hide"    => 400,
    ),
    "erreur"        => array(
        'libel'             => "",
        'backgroundColor'   => 'FFDDDD',
        'color'             => "FF0000",
    ),

    // pour l"application
    "aclReference" => "",
);