<?php
return array(
    "object"        => "odtoggle",
    "typeObj"       => "odcontained",
    "template"      => "odtoggle.twig",
    "label"     => "",
    "position"  => "",
    "dataOn"    => "On",
    "dataOff"   => "Off",
    "size"      => "mini",
    "onStyle"   => "primary",
    "offStyle"  => "default",
    "width"     => "",
    "height"    => "",
    "custom"    => '',
    "resources" => array(
        "css"           => array( "css/bootstrap-toggle.min.css",
                                  "css/bootstrap-toggle-style.css"),
        "js"            => array( "js/bootstrap-toggle.min.js" ),
    )
);