<?php

return array(
    "object"       => "ocinput",
    "typeObj"      => "odcontent",
    "template"     => "ocinput.twig",
    "type"         => "text",
    "size"         => "",
    "maxlength"    => "",
    "label"        => "",
    "state"        => "true",
    "placeholder"  => "",
    'labelWidthBT' => array(),
    'errMessage'   => "",
    'widthBT'      => 12,
    'icon'         => "",
);