<?php

return array(
    "object"       => "ocinput",
    "typeObj"      => "odcontent",
    "template"     => "ocinput.twig",
    "type"         => "text",
    "size"         => "",
    "maxlength"    => "",
    "label"        => "",
    "placeholder"  => "",
    "labelWidthBT" => array(),
    "errMessage"   => "",
    "widthBT"      => 12,
    "icon"         => "",
    "resources" => array(
        "css" => array(  ),
        "js"  => array(  )
    )
);