<?php

return array(
    "object"    => "ocmessage",
    "typeObj"   => "odcontent",
    "template"  => "ocmessage.twig",
    "type"      => "",
    "title"     => "",
    "body"      => "",
    "action"    => "init",
    "sound"     => true,
    "soundPath" => __DIR__ . "/../../../../../public/objets/odcontent/ocmessage/sounds",
    "delay"     => 3000, // en millisecondes
    "position"  => 'bottom right',

    "resources" => array(
        "css" => array( "css/Lobibox.css", ),
        "js"  => array( "js/Lobibox.js", )
    )
);
