<?php

return array(
    "object"         => "occatptcha",
    "typeObj"        => "odcontent",
    "template"       => "occaptcha.twig",
    "label"          => "",
    "labelWidthBT"   => "",
    "length"         => 6,
    "includeNumbers" => false,
    "chars"          => "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789",
    "resource" => array(
        "css" => array(
            "css/jQueryRealPerson/jquery.realperson.css"
        ),
        "js" => array(
            "js/jQueryRealPerson/jquery.plugins.js",
            "js/jQueryRealPerson/jquery.realperson.js"
        ),
    ),
);