<?php

return array(
    "object"         => "occaptcha",
    "typeObj"        => "odcontent",
    "template"       => "occaptcha.twig",
    "label"          => "",
    "labelWidthBT"   => "",
    "length"         => 6,
    "includeNumbers" => false,
    "chars"          => "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789",
    "color"          => "000000",
    "backGround"     => "FFA077",
    "font"           => "PlAGuEdEaTH.ttf",
    "resource" => array(
        "img" => array(
            "img/refresh.jpg",
        ),
        "css" => array(
        ),
        "js" => array(
        ),
    ),
);