<?php

return array(
    "object"         => "occaptcha",
    "typeObj"        => "odcontent",
    "template"       => "occaptcha.twig",
    "label"          => "",
    "labelWidthBT"   => "",
    "length"         => 6,
    "includeNumbers" => false,
    "chars"          => "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789",
    "color"          => rgb(0,0,0),
    "backGround"     => rgb(255, 160, 119),
    "font"           => "PlAGuEdEaTH.ttf",
    "resource" => array(
        "css" => array(
            "css/jQueryRealPerson/jquery.realperson.css"
        ),
        "js" => array(
            "js/jQueryRealPerson/jquery.plugins.js",
            "js/jQueryRealPerson/jquery.realperson.js"
        ),
    ),
);